//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
   
public class AIUtils
{
    public static bool enemyInsideBox(Vector3 Position, Rect BoundBox) {
        Debug.Log(BoundBox.x);
        Debug.Log(Position.x);
        if(Mathf.Abs(Position.x - BoundBox.x) > BoundBox.width / 2 ||
           Mathf.Abs(Position.y - BoundBox.y) > BoundBox.height / 2) {
            return false;
        } else {
            return true;
        }
    }
}
